### PR TITLE
Fix order of execution in CLI toolbar

### LINKED ISSUE #14: Kernel boot time ahead of CSV
I was trying this bundle, without success.

Upon debugging i figured the profiles are filtered out based on kernel boot time (which theoretically makes sense :))

First run:

```
^ "Profile: 2022-07-12 12:25:36"
^ "Kernel:  2022-07-12 12:26:21"
```

Second run:

```
^ "Profile: 2022-07-12 12:26:22"
^ "Kernel:  2022-07-12 12:26:28"
^ "Profile: 2022-07-12 12:25:36"
^ "Kernel:  2022-07-12 12:26:28"
```

Im not entirely sure why profiles are stored first :thinking: nor do i have another solution, but perhaps food for thought.

### PR DESCRIPTION
**Pull request by ro0NL**
fixes #14

### CODE REVIEW

File: src/Console/ProfilerToolbarRenderer.php [hunk 1]
```diff
@@ -242,6 +242,10 @@ private function getWebToolbarCells(Profile $profile): array
             $matches = [];
             preg_match('#sf-toolbar-status-(?P<color>[a-zA-Z]+)#', $toolbarBlock->html(), $matches);
             $color = $matches['color'] ?? null;
+            
+            if ('grey' === $color) {
+                $color = 'default';
+            }
```
Comment (ro0NL) [inline src/Console/ProfilerToolbarRenderer.php:248]: fixes

```
Invalid foreground color specified: "grey".
Expected one of (black, red, green, yellow, blue, magenta, cyan, white, default)
```

**Review by adrienbrault — APPROVED** [review]

**Comment by adrienbrault** [comment]
Makes sense 👍 , thank you for the fix

**Comment by adrienbrault** [comment]
Thank you! I've released [0.1.10](https://github.com/sourceability/console-toolbar-bundle/releases/tag/0.1.10)
